version: '3.8'

services:
  web:
    build: ./biva
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./biva/:/usr/src/biva/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=james
      - POSTGRES_PASSWORD=New$Things1
      - POSTGRES_DB=db

volumes:
  postgres_data: