version: '3.8'
services:
  web:
    build: ./biva
    command: 'gunicorn server.wsgi:application --bind 0.0.0.0:8000'
    expose:
      - '8000:8000'
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - '1337:80'
    depends_on:
      - web
  db:
    image: 'postgres:15'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
    env_file:
      - ./.env.prod.db
volumes:
  postgres_data: null
