# Generated by Django 5.0.3 on 2024-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
