# Generated by Django 5.0.3 on 2024-04-23 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="beautyprofessionalmore",
            name="service_category",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.servicecategory",
            ),
        ),
    ]
